#!/bin/bash
echo "==================================="
echo "EXPO CONNECTION INFO"
echo "==================================="
echo ""
echo "1. Abre Expo Go en tu celular"
echo "2. Escanea el código QR que aparece en la terminal"
echo ""
echo "Si no ves el QR, usa una de estas opciones:"
echo ""
echo "OPCIÓN A - Conexión directa (más estable):"
echo "  1. Asegúrate que tu celular y computadora estén en la misma red WiFi"
echo "  2. En Expo Go, toca 'Enter URL manually'"
echo "  3. Usa: exp://169.254.8.1:8081"
echo ""
echo "OPCIÓN B - Si tienes problemas de red:"
echo "  1. Descarga 'Expo Dev Client' en lugar de 'Expo Go'"
echo "  2. O usa un emulador de Android/iOS"
echo ""
echo "Estado del servidor:"
ps aux | grep "expo start" | grep -v grep && echo "✓ Servidor corriendo" || echo "✗ Servidor detenido"
echo ""
echo "==================================="
